---
- hosts: webservers
  gather_facts: yes
  tasks:
   - name: cache update 
     become: yes
     apt:
      update_cache: yes
   - name: Checking if NGINX is installed
     become: yes
     apt:
      name: nginx
      state: latest
   - name: php-fpm 7.4 installation
     become: yes
     apt:
      name: php7.4-fpm
      state: present
   - name: Duplicating php file
     become: yes
     copy:
       src: index.php
       dest: /var/www/html/
   - name: NGINX starting
     become: yes
     service:
         name: nginx
         state: started
   - name: Adding template file
     become: yes
     template:
       src: nginx.conf
       dest: /etc/nginx/sites-available/default
   - name: Enabling the configuration file from nginx available sites
     become: yes
     file:
       src: /etc/nginx/sites-available/default
       dest: /etc/nginx/sites-enabled/default
       state: link
   - name: Webservers restarting 
     become: yes
     service:
          name: nginx
          state: restarted

- hosts: haproxy
  gather_facts: yes
  become: yes
  tasks:
   - name: haproxy cache update
     apt:
      update_cache: yes
   - name: haproxy installation
     become: yes
     apt:
      name: haproxy
      state: present
   - name: Updating HAProxy config file
     template:
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
   - name: Restarting haproxy
     service:
       name: haproxy
       state: restarted
